"""move card details to wallet

Revision ID: 67c0d5e33b62
Revises: b38969347c00
Create Date: 2026-05-08 18:56:27.748644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c0d5e33b62'
down_revision = 'b38969347c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('card_exp')
        batch_op.drop_column('card_cvc')
        batch_op.drop_column('card_number')

    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('card_cvc', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('card_exp', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_column('card_exp')
        batch_op.drop_column('card_cvc')
        batch_op.drop_column('card_number')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('card_cvc', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('card_exp', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
